### ISSUE TITLE
Error when highlighting option with HTML tags

### ISSUE THREAD

**Issue by redhead** [angular-ui/ui-select#1093]
When I have an option that has HTML tags in it, it throws error trying to highlight it (if the search value matches e.g. `s` in `<strong>`.

    [$sanitize:badparse] The sanitizer was unable to parse the following block of html: </<span class="ui-select-highlight">s</span>trong><br/>...

**Comment by Lecss** [comment]
Updating to a newer version of angular seems to solve it.

**Comment by parliament718** [comment]
I get the same error when trying to highlight "b" and the html already contains a <b></b> tag.

It seems to occur because when it encounters the <b> tag it tries to highlight it like so <<em>b</em>> and that obviously results in bad html. Therefore when using highlighting filter, the input value cannot already have html tags.

**Comment by user378230** [comment]
You should customise your ui-select-choices content rather than trying to apply the highlight filter to a string containing HTML. 

```html
<ui-select ng-model="country.selected" theme="selectize" ng-disabled="disabled" style="width: 300px;">
    <ui-select-match placeholder="Select or search a country in the list...">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="country in countries | filter: $select.search">
      <span ng-bind-html="country.name | highlight: $select.search"></span>
      <small ng-bind-html="country.code | highlight: $select.search"></small>
    </ui-select-choices>
  </ui-select>
```

from http://plnkr.co/edit/SEzrd9vSEmneX4o87UCg?p=preview
