### ISSUE TITLE
Repeat expression parsing is not working

### ISSUE THREAD

**Issue by pdegenhardt** [angular-ui/ui-select#1229]
The following repeat expression is incorrectly parsed:
'item as (key, item) in ctrl.hashList()'.

'ctrl' is read to be the object source and '.hashList()' is read to be the filter.

Also the parseRepeatAttr() function appears to be hard-coded to use a .peopleObj property from the unit test.

**Comment by user378230** [comment]
I believe this has been fixed in more recent versions so closing. (I can't remember the exact commits/PRs to reference here).

If you believe its still relevant please create a new issue with a demo plunkr (or similar) against the latest version of ui-select (currently v0.16.0) along with more detailed information.
