### ISSUE TITLE
Does not update the model. No errors.

### ISSUE THREAD

**Issue by ubombi** [angular-ui/ui-select#1308]
All chosen lements are visible, selecting works good, but model does not update.
Model is empty.
![image](https://cloud.githubusercontent.com/assets/9192931/11212090/3bdfe710-8d3c-11e5-9797-e63c2563c46a.png)

[StackOverflow](http://stackoverflow.com/questions/33756548/why-angular-ui-select-does-not-update-model)
[plunkr demo](http://plnkr.co/edit/dqRJibQiy4IgQF2zxJLh?p=preview)

**Comment by equilerex** [comment]
nothing to do with the plugin... pure angular... you should read up about  prototypal inheritance
https://github.com/angular/angular.js/wiki/Understanding-Scopes

and the solution: (just use $scope.someModel.search_bar instead of $scope.search_bar)
http://plnkr.co/edit/lWHeQumjRVyTOdLW9tI4?p=preview

**Comment by ubombi** [comment]
Thanks, 
Sorry for that)
