### ISSUE TITLE
Doesn't closes if you click inside an iframe

### ISSUE THREAD

**Issue by bsideup** [angular-ui/ui-select#1358]
Hi!

We have layout like this:
```
|---------------------|
| [ui-select]         |
|                     |
| |-----------------| |
| | iframe          | |
| |-----------------| |
|                     |
|---------------------|
```

If Select is open and you click somewhere after select - in closes. But if you click inside an iframe - it doesn't. I suspect this line to be the cause:
https://github.com/angular-ui/ui-select/blob/6f877651fc681627b938361f1f54336733ddf89d/src/uiSelectDirective.js#L165

**Comment by user378230** [comment]
I think this is too specific to your use case/application. 

There are some JS solutions on Stackoverflow which might be useful for you: http://stackoverflow.com/questions/2381336/detect-click-into-iframe-using-javascript/23231136#23231136

But since they aren't reliable or may have unintended side effects, I don't think they will be included in `ui-select`
