### ISSUE TITLE
Background color on focus

### ISSUE THREAD

**Issue by gandaldf** [angular-ui/ui-select#1363]
Hi all, I would like to change my select-ui background color when it is on focus...
I'm using the bootstrap theme but I can't customize it other than the default light-blue shadow around the object.
Can someone please help me?

Thank you

**Comment by user378230** [comment]
Unfortunately we can't provide in depth support to everyone, you should study the included css file. It should be possible to modify it appropriately. (Note you may have to override bootstrap styling too)

You might also wish to try stackoverflow for a great chance of assistance.

**Comment by svaidhyanath** [comment]
I know this issue is closed but just in case if someone came here looking for a solution (like me).. I could not find any help until I decided to dig a little deeper. 

we can achieve the desired effect (background color change on focus for the ui-select bootstrap) with the css rule..

`.ui-select-bootstrap .btn-default-focus > span{
    /*background: (your desired color here)*/
}`

Hope this helps someone.
