### ISSUE TITLE
Multi Selection with close-on-select="false"

### ISSUE THREAD

**Issue by pom-avaleo** [angular-ui/ui-select#1384]
Entered value remains after it's selected for multiple ui-select with close-on-select="false".
http://plnkr.co/edit/BhaOI2Yb6wZDAPXqTkpF?p=preview

**Comment by schan93** [comment]
@pom-avaleo I am having the exact same issue except I didn't declare close-on-select="false".. any ideas why this might be happening?

**Comment by pom-avaleo** [comment]
@schan93 can you paste your code to Plunker?

**Comment by wiibaa** [comment]
@pom-avaleo I think this is the expected behavior by keeping your input it keeps the the listing filtered and let you quickly select a set of value. For example in your plunker, you can type the letter **u** and quickly select all the color with this letter. Anyway this value is cleared when you click out of the field.

Can you explain further what you want to achieve, but at the moment I agree with this "primary" use case.

**Comment by user378230** [comment]
Setting `reset-search-input="true` works as v0.19.4 and resolves this. Closing.
