### ISSUE TITLE
Edit existing tag label

### ISSUE THREAD

**Issue by silentFred** [angular-ui/ui-select#1385]
Hi guys,

Firstly, thank you all for this great set of directives. It's made my word much more bearable! Keep it up!

Does anyone know how I can allow the user to edit the label of a tag in the multiple selection input? At the moment if a user wants to change a custom tag she needs to remove is and re-add.

Thanks in advance!

**Comment by user378230** [comment]
I don't think this is possible by default. You could possibly customise `ui-select-match` contents with some kind of inline edit, something like [angular-xeditable](https://github.com/vitalets/angular-xeditable) might be helpful.

If you come up with something that works be sure to post here, someone else might find it useful too!

**Comment by user378230** [comment]
Closing due to lack of further activity/response.

**Comment by torstenrudolf** [comment]
@user378230 I'm quite interested in this feature.

I got a first basic version working for me with (this change)[https://github.com/Slowvoice/ui-select/commit/08c19d996b649b76d7a73a0d13a64bc3754eee9b].

for demo see (plunker)[http://plnkr.co/edit/gI8ahyqKZoH2rOwwk50E?p=preview]

Do you think the inline editing is necessary in order to get this feature into the project? The downside with my simple approach is that it changes the order of the items I guess (which is not a problem for me).
