### ISSUE TITLE
*** MAINTAIN THIS PROJECT ***

### ISSUE THREAD

**Issue by shali3** [angular-ui/ui-select#1398]
# What is the problem?
There are currently 194 pull requests open and 607 issues. If the original contributors of this project are not willing to continue, please find someone who does. A major pull requester is a good option.
I think this library is too popular to just be neglected.

# How can it be fixed?
If you are reading this and want to contribute to this project, please suggest yourself in the comments below.
![We want you](https://www.podtents.com/wp-content/uploads/2015/10/We-want-you-image.png)

### Side Note
I'm using this library and not a contributor in any way.

**Comment by AdamAxtmann** [comment]
There was a discussion happening about this in #884 but nothing seems to have come of it. The maintainers seem to think ngMaterial is going to replace this so it's not worth maintaining anymore.

**Comment by jcluts** [comment]
Thanks for linking to that discussion @AdamAxtmann, that explains a lot.  It's disappointing to see the repository owner openly stating he believes the project is deprecated and rarely checks in on it anymore.  If that's the case, I'd hope he either transfers the repository or opens the floodgates to new maintainers and pull requests.  

I'm a bit baffled at the assumption we're all going to jump on the ngMaterial bandwagon, to be honest.  Not all of us are chasing the newest and shiniest.  I don't think I'm the only one who appreciates the well established Bootstrap ecosystem (ngMaterial is nowhere close yet), along with it's simple, familiar UI components.

**Comment by gerardp** [comment]
+1

**Comment by shyamal890** [comment]
+1

**Comment by bkyarger** [comment]
:+1:

**Comment by simkessy** [comment]
md-select from mg-material has like 0 options. Why would I use that instead of this, other than the fact it's been completely abandoned.

**Comment by ProLoser** [comment]
@jcluts as the originator of this and variations of this library, I have not really felt ngMaterial serves as a good alternative, as it's kind of a widget suite. But yes, we don't have any people who are really capable of taking ownership of this repo.

**Comment by aaronroberson** [comment]
@ProLoser Please make me a owner/contributor so that I can help maintain this project. Otherwise, I'll be directing others to make PRs on my fork to be published to npm.

I've already accepted several PRs into my fork and have published `ui-select@0.15.0-ar`. 

Folks, If my contributor/owner request is denied and you would like your PRs accepted and published to npm, please send your PR requests to my fork https://github.com/aaronroberson/ui-select and they will be published under the `-ar` namespace. If you would like to submit your PR to angular-ui and to my fork you are encouraged to do so. If you would like to submit someone else's PR which has already been created against angular-ui, you can follow the instructions below:

Navigate to the fork which has initiated the pull request (`pr-fork`) and would like to get published to npm under the `-ar` namespace.
Go to the pull requests page of the initiating fork (`pr-fork`)
Click the `New Pull Request` button.
The pending pull request(s) should be offered. Select on the left side as the base fork (`aaronroberson/ui-select`) (IMPORTANT)
Now the `View Pull Request` button should change to `Create Pull Request`. Click the `Create Pull Request` button.
Now there should be a pending pull request in `aaronroberson/ui-select` which I will accept if the following are true:

1. All tests pass.
3. Feature requests retain the nature of the ui-select, selectize and Select2 projects.
2. Merge conflict instructions are provided for merging the current base (`master` branch) and remote (pull request).
4. Your code is not ambiguous or obscure.

**Comment by ProLoser** [comment]
@aaronroberson added

**Comment by aaronroberson** [comment]
Thank you! I updated my post above to reflect having been added.

**Comment by buremba** [comment]
Good luck @aaronroberson! :100:

**Comment by shali3** [comment]
I vote for @aaronroberson !

**Comment by AdamAxtmann** [comment]
@aaronroberson Glad to see a new maintainer on this project. Do you plan to sift through older PRs?

**Comment by ProLoser** [comment]
@aaronroberson hopefully you've been following along discussions and points I've been making about modularity, simplicity and composeability. I realize that it is somewhat of a pipe dream considering attribute-directives are on the way out but if this project continues expand towards supporting a billion obscure configuration options vs just giving users the bare-bone tools they need to add obscure features themselves it will turn into ui-select2 and all the projects that came before it.

**Comment by shyamal890** [comment]
Closing 600 issues would be a huge task. All the very best @aaronroberson

**Comment by aaronroberson** [comment]
@ProLoser I'm a strong believer in passing in an options config object as opposed to adding a million attributes to a directive. How do you feel about that?

As for modularity, singularity and composability I 100% agree.

**Comment by ProLoser** [comment]
I have explored the ability to do both. Simply iterating for any values on the attributes with a common prefix, letting attributes override properties in the options object, etc.
