### ISSUE TITLE
[Question] Explicit declaration of ui-select module's filter for the logical OR

### ISSUE THREAD

**Issue by toubou91** [angular-ui/ui-select#1510]
The ```propsFilter``` defined in the ```demo.js``` file performs the logical ```OR``` to all the available data for a dropdown and this is correct, as we actually want to perform a search operation to some data.

According to the fore-mentioned words, we come to a conclusion that this filtering should be available by default in the module. So, is there any specific reason that it isn't or I did I miss something?

TB

**Comment by user378230** [comment]
It isn't included as there is nothing special about its relation to ui-select. It is just a normal angular filter that happens to be useful for many peoples use cases when it comes to ui-select. However that doesn't mean everyone needs/wants to use it. 

Since angular provides this extension point itself, it is left up to users to customise how they wish.

**Comment by toubou91** [comment]
I have not read the code for ui-select and angular, but if this is about sth that is not supported by default and the user has to do an additional action (write a specific filter, for example) in order to implement it, where is the point of the selectization, from a modular perspective?

**Comment by user378230** [comment]
I suggest maybe you study the code for ui-select. filter and angular, you will see they are unrelated.  

I appreciate your input, but for now it is acceptable to provide an example in demo so I'm closing this.
