### ISSUE TITLE
Bootstrap theme breaks with resize

### ISSUE THREAD

**Issue by maxbundchen** [angular-ui/ui-select#1575]
When page resizes (any size) the bootstrap theme breaks (tested in Edge and Chrome).

Just open the http://angular-ui.github.io/ui-select/demo-basic.html, resize the window and open the select for search to check.

I noted that when page resizes an 'width: 10px' is added to the input element.

**Comment by maxbundchen** [comment]
A temporary solution is to add some css:

.ui-select-search {
    width: 100% !important;
}

This override the width: 10px added by the javascript code, but I'm not sure what this change could cause.

**Comment by drewfreyling** [comment]
Confirmed in Firefox too.

**Comment by Hectormm** [comment]
Your solution breaks ui-select-multiple

.ui-select-container:not(.ui-select-multiple) input.ui-select-search {
    width: 100% !important;
}

**Comment by andreash** [comment]
This is also the case with the "selectize" theme - couldn't check it with the select2-Theme. Would be great, if that could get fixed. Tried myself to find the root cause - it appears, the sizeSearchInput() is not called, when the search in put becomes visible. But I can't location the point, where it is being made visible (the click on the container).

**Comment by namonlyone84** [comment]
Hello I still see this bug in 0.19.5. I found that the issue is because of wrong jquery selection:
 `container = ctrl.searchInput.parent().parent()[0]` 

it should be parent() one time only:
`container = ctrl.searchInput.parent()[0]`

**Comment by LaniMoo** [comment]
I am also still seeing this bug in 0.19.5.
