### ISSUE TITLE
Select2 styles don't render dropdown is positioned 'up' and theme is globally set

### ISSUE THREAD

**Issue by yogeshgadge** [angular-ui/ui-select#1674]
### Select2 styles don't render dropdown is positioned 'up' and theme is globally set

[ Plunkr ](http://plnkr.co/edit/RgSNxa4bGTwdjABOoyDH?p=preview)

Click on the Always Up Select

**Comment by hearsid** [comment]
To add more clarity to the issue here is some more information and screenshots.
When select2 theme is globally set and and ui-select-choices is set to position='up' then the styling will not be proper, to make the styling work select2 theme has to be manually added to ui-select by theme="select2" . Here is a specific plunker showing the issue clearly, http://plnkr.co/edit/PN9aMYx8ty1m1TN9td2Y .
How it is looking : 
<img width="470" alt="screen shot 2016-06-22 at 12 38 43 pm" src="https://cloud.githubusercontent.com/assets/3892451/16257450/562b8a26-3876-11e6-8534-d1417afee8ff.png">

How it should look:
<img width="423" alt="screen shot 2016-06-22 at 12 38 52 pm" src="https://cloud.githubusercontent.com/assets/3892451/16257463/653428fc-3876-11e6-8038-5ccdf6d53c8b.png">

**Comment by hearsid** [comment]
Here is the link for Pull request for the same, https://github.com/angular-ui/ui-select/pull/1676. Here is the plunk solving the same, http://plnkr.co/edit/PN9aMYx8ty1m1TN9td2Y
