### ISSUE TITLE
select2 with bootstrap example of multiple selection is not working

### ISSUE THREAD

**Issue by Xyroid** [angular-ui/ui-select#1685]
I reached here after searching for select2 for AngularJS application. The example hosted on github.io is not working properly. I can't see the selected values in tagged format. Also rendered UI is messed up.

Example Link: http://angular-ui.github.io/ui-select/demo-select2-with-bootstrap.html
Link to minimally-working plunker that reproduces the issue: http://plnkr.co/edit/DVIyN8YF5fC3m5UZsSr5?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.0

UI-Select: 0.16.1

Bootstrap: 3.1.1

Select2 CSS: 3.4.5

![screenshot_1](https://cloud.githubusercontent.com/assets/2383543/16337519/c4773b10-3a33-11e6-82d6-7d26ae363810.png)

**Comment by kevinbluer** [comment]
Hey @Xyroid, I'm not sure about the rendering issue, but if you need to fix the items not "rendering properly", you can update the **ng-bind** within the **ui-select-match** as per the following:

```
<ui-select-match placeholder="Select up to 3 areas of expertise...">
   <span ng-bind="$item.name"></span>
</ui-select-match>
```

Hope that helps!

**Comment by Xyroid** [comment]
@kevinbluer Yeah it worked, thanks mate!

**Comment by user378230** [comment]
What is it even supposed to look like? :laughing:

**Comment by kevinbluer** [comment]
@user378230...I assume it's not supposed to have the spurious outer boxes, etc.

**Comment by AAlvarez-AlbaStar** [comment]
+1

**Comment by user378230** [comment]
@AAlvarez-AlbaStar and any future commenters: Please don't +1 issues, use github reactions if you must... better yet submit a PR! :+1:

**Comment by Jefiozie** [comment]
Had a look at this issue and saw some difference between the bootstrap and the select2 version.
I have found out that the bootstrap version (where everything works) the multiple is working but the HTML for the ui-select-match is different.

HTML Bootstrap: 
`<ui-select-match placeholder="Select person...">{{$item.name}} &lt;{{$item.email}}&gt;</ui-select-match>`

Code Select2:
`<ui-select-match placeholder="Select or search a person in the list...">{{$select.selected.name}}</ui-select-match>`

After i changed the $select.selected to $item i can add new items to the multiple and it showed me the name of the selected item. As this was already in the bootstrap theme I think this is normal? and somewhere it got changed but not there?

Have made a plunker so that you can look at it.  [Plunker](http://plnkr.co/edit/g7AHMn6cj6Y4subU4KKy?p=preview)
If this is the problem  I will commit a change to the demo page.

**Comment by user378230** [comment]
@Jefiozie this was pointed out by @kevinbluer above. Though a quick PR would be great 😃

**Comment by Jefiozie** [comment]
Damn .. didn't have my  :coffee:  this morning.. will make a pr later for this :+1:

**Comment by Xyroid** [comment]
Still the outer box rendering issue is not fixed :( There's some issue with padding, outer box gets padding from bootstrap's `form-control` class.

**Comment by user378230** [comment]
Whoops this shouldn't have closed.

**Comment by user378230** [comment]
@Xyroid feel free to submit a PR 😃

**Comment by Jefiozie** [comment]
Is this the fix you are looking for: [Plunker](http://plnkr.co/edit/x8vJE1rZCmRTAZUoFolR?p=preview)

**Comment by Xyroid** [comment]
@Jefiozie Yeah, this is what I am looking for. I think you added below lines in CSS. Am I right?

```
.ui-select-container[theme="select2"]{
  padding:0px;
  height:100%;
  border:0;    /* Added by me */
}
```

**Comment by user378230** [comment]
You need to include `select2-bootstrap.css` from the `select2` library. 
Eg.
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2-bootstrap.css">
```

**Comment by Jefiozie** [comment]
@Xyroid did this solve your issue?

**Comment by Xyroid** [comment]
@Jefiozie Yes, it solved the issue. Thanks :+1:
