### ISSUE TITLE
Dropping support for 'selectize' theme?

### ISSUE THREAD

**Issue by dimirc** [angular-ui/ui-select#175]
Not sure how many users actually use the selectize theme, but we might get delays on some features if we need to keep 3 themes in sync.

I've no problem keeping bootstrap and select2 themes (since I actually used them on some projects), but for example I see that some code refactoring might be needed to support selectize in PR https://github.com/angular-ui/ui-select/pull/138 (to support multiselection) since the css on selectize is very specific on the parent/child.

Anyway let me know your thoughts.

**Comment by HadrienPierart** [comment]
No update since last fall, any news on the support of the multi selection for selectize ?
As a matter of fact, Bootstrap and select2 dropdowns are now so used everywhere that selectize style is refreshing.
I have 5 projects using it so pease dont drop the support. And it would be great if multiselect could work with selectize as well... Because for now, I had to remove selectize from 2 others projects as it did not support multiple on selectize...

**Comment by wesleycho** [comment]
This seems like something that isn't happening, so closing unless the new maintainers feel it's something they want to consider - if they view it as an issue, it'd be better for a new issue to be open, this issue seems a bit misleading at this point.
