### ISSUE TITLE
add scroll into ui-select-match

### ISSUE THREAD

**Issue by nitishkumar71** [angular-ui/ui-select#1839]
### Plunker Link:

https://plnkr.co/edit/zVZjcG4rK0tdomfvKK3s

Angular: 1.5.0

UI-Select: Version: 0.19.3 - 2016-08-17T06:24:46.001Z

Bootstrap/Select2/Selectize CSS (if applicable): 0.19.3 - 2016-08-17T06:24:46.066Z

**Comment by Jefiozie** [comment]
In the plunker there is already a scroll so what do you mean? Is this a bug or feature?

**Comment by nitishkumar71** [comment]
If we select more values, size of ui-select textbox increases vertically. What can be done, so that ui-select textbox will not expand in vertical and horizontal direction and we can show all the selected values. 

Suppose if we have a requirement where height and width of ui-select textbox needs to be fixed, as well as we want to show all the values. So, is there a way we can add something like as scroll in ui-select textbox like html <textarea>

**Comment by Jefiozie** [comment]
Can't you just use a fixed height in a custom theme? So that the size is always the same?

**Comment by nitishkumar71** [comment]
edited the demo plunker to show, how it behaves if height is fixed. to fix the height, have commented line 244 in select.css

**Comment by Jefiozie** [comment]
okay now i understand what you meant with this issue. First off i think this is more a stackoverflow question than a "issue".  But to help you out in a direction  could experiment maybe with creating a custom theme where you set a textarea instead of a span. Next to this maybe you can close this issue as it is not a real issue but something in you specific use case. (i believe the behaviour  is normal general behaviour)

**Comment by Jefiozie** [comment]
@nitishkumar71 did i help you out in a way? I still believe this is a thing that needs to be discussed at stackoverflow. As the thing you want is a specific use case and not a bug in the ui-select.

**Comment by nitishkumar71** [comment]
Thank you, I am closing this issue.

**Comment by dmitrysenkovich** [comment]
@nitishkumar71 Hi, have you managed to solve it? Thank you!
