### ISSUE TITLE
Error when doing $compile within the <ui-select> Tag

### ISSUE THREAD

**Issue by pascDa** [angular-ui/ui-select#1856]
### Bug description:
We use a directive that requires ngModel at the same Element (our Directive needs to be at the <ui-select> Tag where the ng-model Attribute is set). Our Directive removes itself, adds other custom directives via setAttribute and compiles the Element again. The Elements HTML was already changed at that Point so a Exception is thrown during $compile.
While $compile the following Exception is thrown:
angular.js:13920 Error: [$compile:ctreq] Controller 'uiSelect', required by directive 'uiSelectSingle', can't be found!

### Link to minimally-working plunker that reproduces the issue:
http://run.plnkr.co/plunks/Y0WtNZgaasUbdx3LvzSn/ 
http://plnkr.co/edit/Y0WtNZgaasUbdx3LvzSn?p=preview 

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.8
UI-Select: 0.19.3
Bootstrap/Select2/Selectize CSS: n/a

**Comment by user378230** [comment]
A recent PR on angular updates the docs to warn that double compliation may cause misbehaving directives: https://github.com/angular/angular.js/pull/15392/files#diff-4148e86088d774bf70bda69fab6f4d4fR385

And the team state that it isn't supported: https://github.com/angular/angular.js/pull/15392#pullrequestreview-8574769

As such I'm going to close this as a usage issue rather than a bug, you're welcome to submit a targeted, unit tested PR if you find a solution.
