### ISSUE TITLE
Failing tests with Angular 1.6

### ISSUE THREAD

**Issue by pete-otaqui** [angular-ui/ui-select#1877]
4 tests fail with Angular 1.6 (the latest version that is installed by default since it's release).

Specifically related to this breaking change between 1.5 and 1.6:

https://github.com/angular/angular.js/commit/e13eeabd7e34a78becec06cfbe72c23f2dcb85f9

Exceptions inside promises are now handled as rejections.

**Comment by Jefiozie** [comment]
Hi @pete-otaqui , this PR was only to support angular version 1.5 and 1.6 right?

I see a lot of problems with new PR's  and it looks like this change has to do with it. 
Thanks for the time.

**Comment by pete-otaqui** [comment]
Hi @Jefiozie 

It was only to support angular 1.6, yes, since it gobbles up errors, and requires you to use angular's own exceptionHandler rather than ... you know ... Javascript's own means for doing that.

What specific problems are you referring to?

**Comment by Jefiozie** [comment]
Hi @pete-otaqui , 

Thanks for the quick reply. 

Since the merge of your PR I see that all  "new" PR's have build errors. I removed your adjustments and as it looks the problems are gone.  (see: #1917 ) 
Still I don't see the root cause of this maybe you  see it? Is it a angular problem or are the test not correct implemented for 1.6.
