### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by Exlord** [angular-ui/ui-select#1881]
Is this library dead? The last commit was a month ago .... and all the pull requests are just sitting there ...

**Comment by amitmawkin** [comment]
looks like the author does not like outside contributions, I did notice it too that PR's are not merged. The performance of this widget is not so great with large datasets , I was wondering if  any PR addresses that, probably update my fork with that code .

**Comment by vicen007** [comment]
@amitmawkin I came to this github for that exact reason. I have a dataset with 2000+ items, and the performance is poor.

**Comment by aaronroberson** [comment]
This library isn't dead, but maintenance is at a slow pace currently. PRs are in fact being looked at and considered. However, we are reluctant to merge in any additional options and new features. The number of options currently in existence is very extensive which is why this project is difficult to maintain. PRs improving performance and addressing bugs are our first priority and are always welcome!
