### ISSUE TITLE
Mismatch in the version number between the package.json and the version in output file

### ISSUE THREAD

**Issue by rdhanasekar** [angular-ui/ui-select#1903]
The ui-select version in the package.json and the version in the comments section of the dist/select.js file is different.

**Comment by Jefiozie** [comment]
Hi, this is correct this is a specific thing for the release. When we release it will bump up to the new "not yet released" version. This way all of our code will get the version as described on release.

**Comment by DmitryGonchar** [comment]
@Jefiozie my 2 cents though - in Release section you have e.g. tag v0.19.6 - the latest version. But when I download it - comment in dist/select.js says v0.19.5. Same for tag 0.19.5 - it says 0.19.4. 

This lead to a confusion and I thought I need to update the component (it was not me who added it to the project), which was not true. Probably build script needs to be fixed so that tag is created with e.g. 0.19.5 version (corresponding to the one in dist/select.js), not with 0.19.6
