### ISSUE TITLE
sanitize error breaks ui-select

### ISSUE THREAD

**Issue by j-walker23** [angular-ui/ui-select#363]
Hey guys. We are doing some XSS testing. We moved to ui-select and away from ui-select2 because of the awesomeness you guys did.

What i am seeing is the control does not allow the xss attack to run which is great, but then the control is broken until refresh. 

I am not sure the intended behavior but is it possible to skip the bad items and still display the safe ones?

Thanks again.

**Comment by wesleycho** [comment]
Can you verify whether this is still an issue?

**Comment by MykhailoIskiv** [comment]
Not sure whether it is the same issue, but I encountered similar issue because of [highlight filter](https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L147) as I have filter with a same name, and my allows html (return $sce.trustAsHtml(text)). Of course I will rename it now and it was my mistake to not use app specific prefix but it might be worth to consider to rename it in UI select as well to avoid possible conflicts with other libs

**Comment by j-walker23** [comment]
I can't remember what this was for or where the code was. But i think i have a memory of not running into this anymore.
