### ISSUE TITLE
multiple: input resizing on container resizing + container padding

### ISSUE THREAD

**Issue by klmdb** [angular-ui/ui-select#582]
When we put padding on .ui-select-container, the input doesn't size properly.
Also, the input doesn't resize when the container's size or padding changes.

I'll create a pull request with my fix.

**Comment by wesleycho** [comment]
Going to close as more information is needed - feel free to open an issue with reproduction in Plunker based on the latest release with more information if this is still an issue.

**Comment by andreash** [comment]
This is also the case with the "selectize" theme - couldn't check it with the select2-Theme. Would be great, if that could get fixed. Tried myself to find the root cause - it appears, the sizeSearchInput() is not called, when the search in put becomes visible. But I can't location the point, where it is being made visible (the click on the container).
