### ISSUE TITLE
Use $parent in ng-repeat on ui-select-choices not working

### ISSUE THREAD

**Issue by upmauro** [angular-ui/ui-select#837]
$parent in ui-select-choices of ui-select not work when used inside directive

I created a plunker snippet to show the problem:

http://plnkr.co/edit/RkPiTdPRHl8eTtCM9lt1?p=preview

Sorry my english.

**Comment by samzhao** [comment]
Hey, I encountered the exact same problem today, and it turns out to be a pretty easy fix.

In your directive's template, instead of saying `<ui-select-choices repeat="item in $parent.list"></ui-select-choices>` do `<ui-select-choices repeat="item in $parent.$parent.list"></ui-select-choices>`.

Hope that helps.

**Comment by wesleycho** [comment]
Closing as a usage issue.

It should be noted that this is an extremely bad practice, and you should stay away from this particular use of $parent at all costs.

**Comment by cyrilchapon** [comment]
Note that I experimented same issue, and `$parent.$parent.list` seems to fix it =D

Even uglier than `$parent` =D
