### ISSUE TITLE
Using objects in <ui-select-choices repeat="">

### ISSUE THREAD

**Issue by blowsie** [angular-ui/ui-select#971]
Forgive me if this has already been asked, I couldn't find a ticket for it.

I'm migrating from **ui-select2**, which allowed me to use objects as my data for example:

```
var data = {
    'Adam': {
        age: 10,
        location: 'UK'
    }
}

HTML
<select data-ng-options="value as key for (key, value) in data">
```

How can I use an object as my data in **ui-select**?
I tried `data-repeat="name in data"` but got `[ui.select:items] Expected an array but got {"Adam"...`

**Comment by Andrewpk** [comment]
👍

**Comment by blowsie** [comment]
@Andrewpk did you manage to figure out a solution? Changing the object to an array is a last resort for me for performance reasons.

**Comment by Andrewpk** [comment]
I just ended up switching to angular-chosen which supports both arrays and objects as data sources.

**Comment by akotlar** [comment]
Agreed, I think this is a major limitation. The source clearly expects items to be in the 

"item in array" with an optional track by: see line 1774

 var match = expression.match(/^\s*(?:([\s\S]+?)\s+as\s+)?([\S]+?)\s+in\s+([\s\S]+?)(?:\s+track\s+by\s+([\s\S]+?))?\s*$/);

This can be changed to 

 var match = expression.match(/^\s*(?:([\s\S]+?)\s+as\s+)?([\S]+?)\s+.*\s+in\s+([\s\S]+?)(?:\s+track\s+by\s+([\s\S]+?))?\s*$/);

and will pick up matches, but further modifications are needed in order to return items. 

It wold be really useful to allow standard ng-options syntax; this seems like a major limitation.

**Comment by dimirc** [comment]
PR https://github.com/angular-ui/ui-select/pull/1208 should resolve this
